(add-to-list 'load-path user-emacs-directory)
(add-to-list 'load-path (concat user-emacs-directory "config"))
(add-to-list 'load-path (concat user-emacs-directory "elisp"))
(add-to-list 'load-path (concat user-emacs-directory "themes"))
(add-to-list 'load-path (concat user-emacs-directory "vendor/"))

(require 'cl)

(require 'init-packages)
(require 'init-utils)
(require 'init-core)
(require 'init-ido)
(require 'init-projects)
(require 'init-git)
(require 'init-elisp)
(require 'init-ruby)
(require 'init-rails)
(require 'init-handlebars)
(require 'init-eyecandy)
